from __future__ import annotations
 
import re
import tempfile
import datetime
from dataclasses import dataclass, field
from pathlib import Path
 
from vault.cli.logger import blank, done, log, section, step, warn
 
VAULT_SECTION_HEADER = "## Related notes (vault)"
VAULT_LINK_MARKER = "<!-- vault:backlink -->"


@dataclass
class WriteResult:
    path: Path
    link: str
    success: bool = True
    skipped: bool = False
    dry_run: bool = False
    error:   str  = ""



def write_backlink(source_path: Path, target_title: str, dry_run: bool = False) -> WriteResult:
    link_text = f"[[{target_title}]]"
 
    step("WRITE", f"Adding {link_text} to [bold]{source_path.name}[/bold]")
    log(f"File: {source_path}")
    log(f"Link: {link_text}  {VAULT_LINK_MARKER}")
    log("Idempotency check: scan file for existing link before writing")
 
    if not source_path.exists():
        warn("WRITE", f"File not found: {source_path}")
        return WriteResult(path=source_path, link=link_text, success=False, error="File not found")
 
    content = source_path.read_text(encoding="utf-8")
 
    if link_text in content:
        log(f"  [dim]{link_text} already present - skipping[/dim]")
        done("WRITE", "Skipped (link already exists)")

        return WriteResult(path=source_path, link=link_text, skipped=True, dry_run=dry_run)
 
    new_line = f"- {link_text}  {VAULT_LINK_MARKER}"
 
    if VAULT_SECTION_HEADER in content:
        log("  Appending to existing 'Related notes (vault)' section")
        new_content = content.rstrip() + f"\n{new_line}\n"
    else:
        log("  Creating new 'Related notes (vault)' section at end of file")
        new_content = content.rstrip() + f"\n\n---\n{VAULT_SECTION_HEADER}\n{new_line}\n"
 
    if dry_run:
        log("  [yellow]DRY RUN - file not modified[/yellow]")
        log(f"  Would append: {new_line}")
        done("WRITE", f"Dry run - would add {link_text}")

        return WriteResult(path=source_path, link=link_text, dry_run=True)
 
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8",
            dir=source_path.parent, delete=False, suffix=".tmp"
        ) as tmp:
            tmp.write(new_content)
            tmp_path = Path(tmp.name)

        tmp_path.replace(source_path)

        log("  [green]Written successfully (atomic rename)[/green]")
        done("WRITE", f"Added {link_text} to {source_path.name}")
        
        return WriteResult(path=source_path, link=link_text)
    except OSError as exc:
        warn("WRITE", f"Write failed: {exc}")
        return WriteResult(path=source_path, link=link_text, success=False, error=str(exc))


def write_backlink_pair(
    source_path: Path, source_title: str,
    target_path: Path, target_title: str,
    dry_run: bool = False,
) -> tuple[WriteResult, WriteResult]:
    # Write biderectional backlink pairs between two notes

    section("Write backlink pair")
    log(f"Bidirectional: [{source_title}]  <-->  [{target_title}]")
    log("Both files will be updated to reference each other")

    if dry_run:
        log("[yellow]DRY RUN mode - no files will be modified[/yellow]")

    blank()
 
    r1 = write_backlink(source_path, target_title, dry_run=dry_run)
    blank()
    r2 = write_backlink(target_path, source_title, dry_run=dry_run)

    return r1, r2

def write_synthesis(
    vault_path: Path,
    title: str,
    content: str,
    source_titles: list[str],
    tags: list[str] | None = None,
    dry_run: bool = False,
) -> Path | None:
    # Write a cross-note synthesis as a new .md file in the vault.

    section("Write synthesis")
    step("SYNTHESIS", f"Saving synthesis note: [bold]{title}[/bold]")
    log(f"Synthesizing {len(source_titles)} source note(s):")

    for t in source_titles:
        log(f"  - [[{t}]]")
 
    safe_name = re.sub(r'[<>:"/\\|?*]', "", title).strip()[:80]
    file_path = vault_path / f"{safe_name}.md"

    log(f"Output path: {file_path}")
 
    all_tags = list(set(["vault-synthesis"] + (tags or [])))
    today = datetime.date.today().isoformat()
    source_links = "\n".join(f"- [[{t}]]" for t in source_titles)
 
    frontmatter = (
        f"---\ntitle: {title}\ndate: {today}\n"
        f"tags: [{', '.join(all_tags)}]\n"
        f"synthesized_from:\n"
        + "\n".join(f"  - {t}" for t in source_titles)
        + "\n---\n"
    )
    full_content = (
        f"{frontmatter}\n# {title}\n\n{content}\n\n"
        f"---\n## Source notes\n\n{source_links}\n\n"
        f"*Generated by vault on {today}*\n"
    )
 
    if dry_run:
        log("[yellow]DRY RUN - file not written[/yellow]")
        log(f"Would create: {file_path}")
        done("SYNTHESIS", "Dry run complete")

        return file_path
 
    if file_path.exists():
        warn("SYNTHESIS", f"{file_path.name} already exists - skipping to avoid overwrite")
        return None
 
    try:
        file_path.write_text(full_content, encoding="utf-8")

        log(f"[green]Written: {file_path.name}[/green]")
        done("SYNTHESIS", f"Synthesis note saved: {file_path.name}")

        return file_path
    except OSError as exc:
        warn("SYNTHESIS", f"Write failed: {exc}")
        return None